version: "3"

services:
  mongo:
    image: mongo:latest
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - caro-studio-mongo-data:/data/db

volumes:
  caro-studio-mongo-data:

networks:
  caro-studio_internal:


